viewModels.apply_register = {
  id:"964217b7-0f66-4e95-a017-7492d6c8f947",
  name:"apply_register",
  dataName:"apply_register",
  colModel:[
    {name:"ncpRowSelect", label:" ", width:20, hidden:false, sortable:false, search:false, resizable:false, editable:false, canEdit:false, edittype:"checkbox", dispunitType:"checkbox"},    {name:"ispass", label:"是否通过", width:100, hidden:false, sortable:false, search:false, resizable:false, editable:true, canEdit:true, edittype:"checkbox", dispunitType:"checkbox"},
    {name:"id", label:"ID", width:0, hidden:true, sortable:false, search:false, resizable:false, editable:true, canEdit:false, edittype:"text", dispunitType:"text"},
    {name:"username", label:"用户名", width:100, hidden:false, sortable:false, search:false, resizable:false, editable:true, canEdit:true, edittype:"text", dispunitType:"text"},
    {name:"phoneno", label:"电话号", width:100, hidden:false, sortable:false, search:false, resizable:false, editable:true, canEdit:true, edittype:"text", dispunitType:"text"},
    {name:"password", label:"密码", width:100, hidden:true, sortable:false, search:false, resizable:false, editable:true, canEdit:false, edittype:"text", dispunitType:"text"},
    {name:"qq", label:"QQ", width:100, hidden:false, sortable:false, search:false, resizable:false, editable:true, canEdit:true, edittype:"text", dispunitType:"text"},
    {name:"shopname", label:"店铺名称", width:150, hidden:false, sortable:false, search:false, resizable:false, editable:true, canEdit:true, edittype:"text", dispunitType:"text"},
    {name:"shopprovince", label:"省", width:100, hidden:false, sortable:false, search:false, resizable:false, editable:true, canEdit:true, edittype:"text", dispunitType:"text"},
    {name:"shopticy", label:"市", width:100, hidden:false, sortable:false, search:false, resizable:false, editable:true, canEdit:true, edittype:"text", dispunitType:"text"},
    {name:"shopcountry", label:"县", width:100, hidden:false, sortable:false, search:false, resizable:false, editable:true, canEdit:true, edittype:"text", dispunitType:"text"},
    {name:"shopaddress", label:"地址", width:150, hidden:false, sortable:false, search:false, resizable:false, editable:true, canEdit:true, edittype:"text", dispunitType:"text"},
    {name:"channel", label:"来源", width:100, hidden:false, sortable:false, search:false, resizable:false, editable:true, canEdit:true, edittype:"text", dispunitType:"text"},
    {name:"licensepath", label:"营业执照地址", width:100, hidden:false, sortable:false, search:false, resizable:false, editable:true, canEdit:true, edittype:"text", dispunitType:"text"},
    {name:"checkuserid", label:"审批用户ID", width:100, hidden:true, sortable:false, search:false, resizable:false, editable:true, canEdit:false, edittype:"text", dispunitType:"text"},
    {name:"checkuser", label:"审批用户", width:100, hidden:false, sortable:false, search:false, resizable:false, editable:true, canEdit:true, edittype:"text", dispunitType:"text"},
    {name:"submittime", label:"提交时间", width:100, hidden:false, sortable:false, search:false, resizable:false, editable:true, canEdit:true, edittype:"text", formatter:timeFormater, dispunitType:"time"},
    {name:"checktime", label:"审批时间", width:100, hidden:false, sortable:false, search:false, resizable:false, editable:true, canEdit:true, edittype:"text", formatter:timeFormater, dispunitType:"time"}
  ],
  dispUnitModel:[
    {name:"ispass", label:"是否通过", editable:true,dispunitType:"checkbox", },
    {name:"id", label:"ID", editable:false,dispunitType:"text", },
    {name:"username", label:"用户名", editable:true,dispunitType:"text", },
    {name:"phoneno", label:"电话号", editable:true,dispunitType:"text", },
    {name:"password", label:"密码", editable:false,dispunitType:"text", },
    {name:"qq", label:"QQ", editable:true,dispunitType:"text", },
    {name:"shopname", label:"店铺名称", editable:true,dispunitType:"text", },
    {name:"shopprovince", label:"省", editable:true,dispunitType:"text", },
    {name:"shopticy", label:"市", editable:true,dispunitType:"text", },
    {name:"shopcountry", label:"县", editable:true,dispunitType:"text", },
    {name:"shopaddress", label:"地址", editable:true,dispunitType:"text", },
    {name:"channel", label:"来源", editable:true,dispunitType:"text", },
    {name:"licensepath", label:"营业执照地址", editable:true,dispunitType:"text", },
    {name:"checkuserid", label:"审批用户ID", editable:false,dispunitType:"text", },
    {name:"checkuser", label:"审批用户", editable:true,dispunitType:"text", },
    {name:"submittime", label:"提交时间", editable:true,dispunitType:"time", },
    {name:"checktime", label:"审批时间", editable:true,dispunitType:"time", }
  ]
}
