viewModels.dmdt_bi_strainspaper = {
  id:"e884668b-3235-4d45-80d8-6766c2ccf0bf",
  name:"dmdt_bi_strainspaper",
  dataName:"dmdt_bi_strainspaper",
  colModel:[
    {name:"ncpRowSelect", label:" ", width:20, hidden:false, sortable:false, search:false, resizable:false, editable:false, canEdit:false, nullable:true, edittype:"checkbox", dispunitType:"checkbox"},
    {name:"id", label:"id", width:0, hidden:true, sortable:false, search:false, resizable:false, editable:true, canEdit:false, nullable:false, edittype:"text", dispunitType:"text"},
    {name:"species", label:"种", width:140, hidden:false, sortable:true, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"genus", label:"属", width:30, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"speciescn", label:"种(中文)", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"genuscn", label:"属(中文)", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"searchsite", label:"搜索网站", width:30, hidden:false, sortable:false, search:true, resizable:true, editable:true, canEdit:true, nullable:false, edittype:"text", dispunitType:"text"},
    {name:"listfilepath", label:"列表文件路径", width:30, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"sourcefilefolder", label:"原始文件目录", width:30, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:false, edittype:"text", dispunitType:"text"},
    {name:"txtfilefolder", label:"文本文件目录", width:30, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:false, edittype:"text", dispunitType:"text"},
    {name:"importdefinition", label:"导入定义", width:30, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"list"},
    {name:"detailcount", label:"明细条数", width:30, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:false, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"txtfilecount", label:"文本文件数", width:30, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:false, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"bothfilecount", label:"双性文数", width:30, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:false, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"bothsentancecount", label:"双性句数", width:30, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:false, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"negativefilecount", label:"阴性文数", width:30, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:false, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"negativesentancecount", label:"阴性句数", width:30, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:false, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"positivefilecount", label:"阳性文数", width:30, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:false, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"positivesentancecount", label:"阳性句数", width:30, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:false, nullable:true, edittype:"text", dispunitType:"decimal"},
    {name:"featuremachine", label:"特征(机器)", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"featuremanual", label:"特征(手工)", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"importdefinitionid", label:"导入定义id", width:0, hidden:true, sortable:false, search:false, resizable:false, editable:true, canEdit:false, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"createtime", label:"导入时间", width:30, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:false, nullable:true, edittype:"text", formatter:timeFormater, dispunitType:"time"},
    {name:"createuser", label:"导入人", width:0, hidden:true, sortable:true, search:true, resizable:true, editable:true, canEdit:false, nullable:true, edittype:"text", dispunitType:"pop"},
    {name:"createuserid", label:"导入人id", width:0, hidden:true, sortable:false, search:false, resizable:false, editable:true, canEdit:false, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"createusercode", label:"导入人编码", width:30, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:false, nullable:true, edittype:"text", dispunitType:"text"}
  ],
  dispUnitModel:[
    {name:"id", label:"id", editable:false,nullable:false, hidden:true, dispunitType:"text", },
    {name:"species", label:"种", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"genus", label:"属", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"speciescn", label:"种(中文)", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"genuscn", label:"属(中文)", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"searchsite", label:"搜索网站", editable:true,nullable:false, hidden:false, dispunitType:"text", },
    {name:"listfilepath", label:"列表文件路径", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"sourcefilefolder", label:"原始文件目录", editable:true,nullable:false, hidden:false, dispunitType:"text", },
    {name:"txtfilefolder", label:"文本文件目录", editable:true,nullable:false, hidden:false, dispunitType:"text", },
    {name:"importdefinition", label:"导入定义", editable:true,nullable:true, hidden:false, dispunitType:"list", },
    {name:"detailcount", label:"明细条数", editable:false,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"txtfilecount", label:"文本文件数", editable:false,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"bothfilecount", label:"双性文数", editable:false,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"bothsentancecount", label:"双性句数", editable:false,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"negativefilecount", label:"阴性文数", editable:false,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"negativesentancecount", label:"阴性句数", editable:false,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"positivefilecount", label:"阳性文数", editable:false,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"positivesentancecount", label:"阳性句数", editable:false,nullable:true, hidden:false, dispunitType:"decimal", },
    {name:"featuremachine", label:"特征(机器)", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"featuremanual", label:"特征(手工)", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"importdefinitionid", label:"导入定义id", editable:false,nullable:true, hidden:true, dispunitType:"text", },
    {name:"createtime", label:"导入时间", editable:false,nullable:true, hidden:false, dispunitType:"time", },
    {name:"createuser", label:"导入人", editable:false,nullable:true, hidden:true, dispunitType:"pop", },
    {name:"createuserid", label:"导入人id", editable:false,nullable:true, hidden:true, dispunitType:"text", },
    {name:"createusercode", label:"导入人编码", editable:false,nullable:true, hidden:false, dispunitType:"text", }
  ]
}
