viewModels.ie_dxbkzyxx = {
  id:"9f76dea0-7473-48a5-bd95-731d688371fa",
  name:"ie_dxbkzyxx",
  dataName:"ie_dxbkzyxx",
  colModel:[
    {name:"ncpRowSelect", label:" ", width:20, hidden:false, sortable:false, search:false, resizable:false, editable:false, canEdit:false, nullable:true, edittype:"checkbox", dispunitType:"checkbox"},
    {name:"xw", label:"学位", width:100, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"xkfl", label:"学科分类", width:100, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"pop"},
    {name:"yjxk", label:"一级学科", width:100, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"zy", label:"专业", width:100, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"zydm", label:"专业代码", width:100, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"zypymb", label:"专业培养目标", width:200, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"zyxxfx", label:"专业学习方向", width:200, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"bysyhdyxjfmdzzhnl", label:"毕业生应获得以下几方面的知识和能力", width:200, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"zykc", label:"主要课程", width:200, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"zysjxjxhj", label:"主要实践性教学环节", width:200, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"xynx", label:"修业年限", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"syxw", label:"授予学位", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"jyfx", label:"就业方向", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"url", label:"url", width:200, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"id", label:"ID", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"parentid", label:"parentid", width:0, hidden:true, sortable:true, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"createtime", label:"记录创建时间", width:0, hidden:true, sortable:true, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", formatter:timeFormater, dispunitType:"time"},
    {name:"isdeleted", label:"已删除", width:50, hidden:true, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"checkbox", dispunitType:"checkbox"}
  ],
  dispUnitModel:[
    {name:"xw", label:"学位", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"xkfl", label:"学科分类", editable:true,nullable:true, hidden:false, dispunitType:"pop", },
    {name:"yjxk", label:"一级学科", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"zy", label:"专业", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"zydm", label:"专业代码", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"zypymb", label:"专业培养目标", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"zyxxfx", label:"专业学习方向", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"bysyhdyxjfmdzzhnl", label:"毕业生应获得以下几方面的知识和能力", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"zykc", label:"主要课程", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"zysjxjxhj", label:"主要实践性教学环节", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"xynx", label:"修业年限", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"syxw", label:"授予学位", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"jyfx", label:"就业方向", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"url", label:"url", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"id", label:"ID", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"parentid", label:"parentid", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"createtime", label:"记录创建时间", editable:true,nullable:true, hidden:true, dispunitType:"time", },
    {name:"isdeleted", label:"已删除", editable:true,nullable:true, hidden:true, dispunitType:"checkbox", }
  ]
}
