viewModels.ie_jz_xm = {
  id:"e901a3e3-fe57-4f18-92a2-3a3e0f8670ff",
  name:"ie_jz_xm",
  dataName:"ie_jz_xm",
  colModel:[
    {name:"ncpRowSelect", label:" ", width:20, hidden:false, sortable:false, search:false, resizable:false, editable:false, canEdit:false, nullable:true, edittype:"checkbox", dispunitType:"checkbox"},
    {name:"xmbh", label:"项目编号", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"sjxmbh", label:"省级项目编号", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"xmmc", label:"项目名称", width:120, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"szqh", label:"所在区划", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"jsdw", label:"建设单位", width:120, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"jsdwzzjgdm", label:"建设单位组织机构代码（统一社会信用代码）", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"xmfl", label:"项目分类", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"jsxz", label:"建设性质", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"gcyt", label:"工程用途", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"ztz", label:"总投资", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"zmj", label:"总面积", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"lxjb", label:"立项级别", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"lxwh", label:"立项文号", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"id", label:"ID", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"parentid", label:"parentid", width:0, hidden:true, sortable:true, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"createtime", label:"记录创建时间", width:0, hidden:true, sortable:true, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", formatter:timeFormater, dispunitType:"time"},
    {name:"isdeleted", label:"已删除", width:50, hidden:true, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"checkbox", dispunitType:"checkbox"}
  ],
  dispUnitModel:[
    {name:"xmbh", label:"项目编号", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"sjxmbh", label:"省级项目编号", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"xmmc", label:"项目名称", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"szqh", label:"所在区划", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"jsdw", label:"建设单位", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"jsdwzzjgdm", label:"建设单位组织机构代码（统一社会信用代码）", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"xmfl", label:"项目分类", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"jsxz", label:"建设性质", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"gcyt", label:"工程用途", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"ztz", label:"总投资", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"zmj", label:"总面积", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"lxjb", label:"立项级别", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"lxwh", label:"立项文号", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"id", label:"ID", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"parentid", label:"parentid", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"createtime", label:"记录创建时间", editable:true,nullable:true, hidden:true, dispunitType:"time", },
    {name:"isdeleted", label:"已删除", editable:true,nullable:true, hidden:true, dispunitType:"checkbox", }
  ]
}
