viewModels.ie_klxxlb = {
  id:"2d17c7e1-8629-43f2-be8a-a4ef3211470d",
  name:"ie_klxxlb",
  dataName:"ie_klxxlb",
  colModel:[
    {name:"ncpRowSelect", label:" ", width:20, hidden:false, sortable:false, search:false, resizable:false, editable:false, canEdit:false, nullable:true, edittype:"checkbox", dispunitType:"checkbox"},
    {name:"name", label:"name", width:100, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"name_cn", label:"name_cn", width:100, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"pop", label:"pop", width:50, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"body_length", label:"body_length", width:50, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"description", label:"description", width:200, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"diet", label:"diet", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"diet_cn", label:"diet_cn", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"area", label:"area", width:100, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"area_cn", label:"area_cn", width:100, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"area_code", label:"area_code", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"full_period", label:"full_period", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"period_en", label:"period_en", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"period_cn", label:"period_cn", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"years_ago", label:"years_ago", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"full_period_cn", label:"full_period_cn", width:200, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"teeth", label:"teeth", width:50, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"how_it_moved", label:"how_it_moved", width:50, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"food", label:"food", width:50, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"content", label:"content", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"taxonomy", label:"taxonomy", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"type_species", label:"type_species", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"id", label:"ID", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"parentid", label:"parentid", width:0, hidden:true, sortable:true, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"createtime", label:"记录创建时间", width:0, hidden:true, sortable:true, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", formatter:timeFormater, dispunitType:"time"},
    {name:"isdeleted", label:"已删除", width:0, hidden:false, sortable:false, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"checkbox", dispunitType:"checkbox"}
  ],
  dispUnitModel:[
    {name:"name", label:"name", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"name_cn", label:"name_cn", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"pop", label:"pop", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"body_length", label:"body_length", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"description", label:"description", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"diet", label:"diet", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"diet_cn", label:"diet_cn", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"area", label:"area", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"area_cn", label:"area_cn", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"area_code", label:"area_code", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"full_period", label:"full_period", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"period_en", label:"period_en", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"period_cn", label:"period_cn", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"years_ago", label:"years_ago", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"full_period_cn", label:"full_period_cn", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"teeth", label:"teeth", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"how_it_moved", label:"how_it_moved", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"food", label:"food", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"content", label:"content", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"taxonomy", label:"taxonomy", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"type_species", label:"type_species", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"id", label:"ID", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"parentid", label:"parentid", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"createtime", label:"记录创建时间", editable:true,nullable:true, hidden:true, dispunitType:"time", },
    {name:"isdeleted", label:"已删除", editable:true,nullable:true, hidden:false, dispunitType:"checkbox", }
  ]
}
