viewModels.ie_qglsjzxm = {
  id:"a9cc1050-273e-45eb-bd1a-5ec0340cd394",
  name:"ie_qglsjzxm",
  dataName:"ie_qglsjzxm",
  colModel:[
    {name:"ncpRowSelect", label:" ", width:20, hidden:false, sortable:false, search:false, resizable:false, editable:false, canEdit:false, nullable:true, edittype:"checkbox", dispunitType:"checkbox"},
    {name:"xmmc", label:"项目名称", width:200, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"xmdd", label:"项目地点", width:200, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"rzlb", label:"认证类别", width:100, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"zygn", label:"主要功能", width:200, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"tzdw", label:"投资单位", width:200, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"zxdw", label:"咨询单位", width:200, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"rzsj", label:"认证时间", width:100, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"jzmj", label:"建筑面积", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"sjdw", label:"设计单位", width:200, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"sgdw", label:"施工单位", width:200, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"xmjj", label:"项目简介", width:300, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"lat", label:"lat", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"lng", label:"lng", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"id", label:"ID", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"parentid", label:"parentid", width:0, hidden:true, sortable:true, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"createtime", label:"记录创建时间", width:0, hidden:true, sortable:true, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", formatter:timeFormater, dispunitType:"time"},
    {name:"isdeleted", label:"已删除", width:50, hidden:false, sortable:false, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"checkbox", dispunitType:"checkbox"}
  ],
  dispUnitModel:[
    {name:"xmmc", label:"项目名称", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"xmdd", label:"项目地点", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"rzlb", label:"认证类别", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"zygn", label:"主要功能", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"tzdw", label:"投资单位", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"zxdw", label:"咨询单位", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"rzsj", label:"认证时间", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"jzmj", label:"建筑面积", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"sjdw", label:"设计单位", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"sgdw", label:"施工单位", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"xmjj", label:"项目简介", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"lat", label:"lat", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"lng", label:"lng", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"id", label:"ID", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"parentid", label:"parentid", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"createtime", label:"记录创建时间", editable:true,nullable:true, hidden:true, dispunitType:"time", },
    {name:"isdeleted", label:"已删除", editable:true,nullable:true, hidden:false, dispunitType:"checkbox", }
  ]
}
