viewModels.ie_qgspfxqxx = {
  id:"d9af900a-e053-4efd-80ce-8b5725a11444",
  name:"ie_qgspfxqxx",
  dataName:"ie_qgspfxqxx",
  colModel:[
    {name:"ncpRowSelect", label:" ", width:20, hidden:false, sortable:false, search:false, resizable:false, editable:false, canEdit:false, nullable:true, edittype:"checkbox", dispunitType:"checkbox"},
    {name:"csbm", label:"城市编码", width:100, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"csmc", label:"城市名称", width:100, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"qybm", label:"区域编码", width:100, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"qymc", label:"区域名称", width:100, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"jdbm", label:"街道编码", width:100, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"jdmc", label:"街道名称", width:100, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"xqmc", label:"小区名称", width:200, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"lat", label:"lat", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"lng", label:"lng", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"dz", label:"地址", width:300, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"dsts", label:"待售套数", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"jsnf", label:"建设年份", width:100, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"jj", label:"均价", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"url", label:"url", width:200, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"id", label:"ID", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"parentid", label:"parentid", width:0, hidden:true, sortable:true, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"createtime", label:"记录创建时间", width:0, hidden:true, sortable:true, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", formatter:timeFormater, dispunitType:"time"},
    {name:"isdeleted", label:"已删除", width:50, hidden:false, sortable:false, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"checkbox", dispunitType:"checkbox"}
  ],
  dispUnitModel:[
    {name:"csbm", label:"城市编码", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"csmc", label:"城市名称", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"qybm", label:"区域编码", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"qymc", label:"区域名称", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"jdbm", label:"街道编码", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"jdmc", label:"街道名称", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"xqmc", label:"小区名称", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"lat", label:"lat", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"lng", label:"lng", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"dz", label:"地址", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"dsts", label:"待售套数", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"jsnf", label:"建设年份", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"jj", label:"均价", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"url", label:"url", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"id", label:"ID", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"parentid", label:"parentid", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"createtime", label:"记录创建时间", editable:true,nullable:true, hidden:true, dispunitType:"time", },
    {name:"isdeleted", label:"已删除", editable:true,nullable:true, hidden:false, dispunitType:"checkbox", }
  ]
}
