viewModels.ie_qgmsdpxx = {
  id:"e7176d52-b661-49ea-8bae-231dec9dbf3a",
  name:"ie_qgmsdpxx",
  dataName:"ie_qgmsdpxx",
  colModel:[
    {name:"ncpRowSelect", label:" ", width:20, hidden:false, sortable:false, search:false, resizable:false, editable:false, canEdit:false, nullable:true, edittype:"checkbox", dispunitType:"checkbox"},
    {name:"cs", label:"城市", width:100, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"ssqy", label:"所属区域", width:100, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"dpmc", label:"店铺名称", width:200, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"dpbm", label:"店铺编码", width:100, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"dz", label:"地址", width:300, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"dh", label:"电话", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"lx", label:"类型", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"pls", label:"评论数", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"lat", label:"lat", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"lng", label:"lng", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"rjjg", label:"人均价格", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"kwpf", label:"口味评分", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"hjpf", label:"环境评分", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"fwpf", label:"服务评分", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"id", label:"ID", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"parentid", label:"parentid", width:0, hidden:true, sortable:true, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"createtime", label:"记录创建时间", width:0, hidden:true, sortable:true, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", formatter:timeFormater, dispunitType:"time"},
    {name:"isdeleted", label:"已删除", width:50, hidden:true, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"checkbox", dispunitType:"checkbox"}
  ],
  dispUnitModel:[
    {name:"cs", label:"城市", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"ssqy", label:"所属区域", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"dpmc", label:"店铺名称", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"dpbm", label:"店铺编码", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"dz", label:"地址", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"dh", label:"电话", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"lx", label:"类型", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"pls", label:"评论数", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"lat", label:"lat", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"lng", label:"lng", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"rjjg", label:"人均价格", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"kwpf", label:"口味评分", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"hjpf", label:"环境评分", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"fwpf", label:"服务评分", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"id", label:"ID", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"parentid", label:"parentid", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"createtime", label:"记录创建时间", editable:true,nullable:true, hidden:true, dispunitType:"time", },
    {name:"isdeleted", label:"已删除", editable:true,nullable:true, hidden:true, dispunitType:"checkbox", }
  ]
}
