viewModels.ie_user_umassd_pilot_basic = {
  id:"549e6bdc-3a7a-48b0-82a8-8658ae114a5d",
  name:"ie_user_umassd_pilot_basic",
  dataName:"ie_user_umassd_pilot_basic",
  colModel:[
    {name:"ncpRowSelect", label:" ", width:20, hidden:false, sortable:false, search:false, resizable:false, editable:false, canEdit:false, nullable:true, edittype:"checkbox", dispunitType:"checkbox"},
    {name:"street2", label:"STREET 2", width:0, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"city", label:"CITY", width:0, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"med_exp_date", label:"MED EXP DATE", width:0, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"med_date", label:"MED DATE", width:0, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"med_class", label:"MED CLASS", width:0, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"first_name", label:"FIRST NAME", width:0, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"street1", label:"STREET 1", width:0, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"region", label:"REGION", width:0, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"last_name", label:"LAST NAME", width:0, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"zip_code", label:"ZIP CODE", width:0, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"unique_id", label:"UNIQUE ID", width:0, hidden:false, sortable:true, search:true, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"state", label:"STATE", width:0, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"country", label:"COUNTRY", width:0, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"id", label:"ID", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"parentid", label:"parentid", width:0, hidden:true, sortable:true, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", dispunitType:"text"},
    {name:"createtime", label:"记录创建时间", width:0, hidden:true, sortable:true, search:false, resizable:true, editable:true, canEdit:true, nullable:true, edittype:"text", formatter:timeFormater, dispunitType:"time"}
  ],
  dispUnitModel:[
    {name:"street2", label:"STREET 2", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"city", label:"CITY", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"med_exp_date", label:"MED EXP DATE", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"med_date", label:"MED DATE", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"med_class", label:"MED CLASS", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"first_name", label:"FIRST NAME", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"street1", label:"STREET 1", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"region", label:"REGION", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"last_name", label:"LAST NAME", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"zip_code", label:"ZIP CODE", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"unique_id", label:"UNIQUE ID", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"state", label:"STATE", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"country", label:"COUNTRY", editable:true,nullable:true, hidden:false, dispunitType:"text", },
    {name:"id", label:"ID", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"parentid", label:"parentid", editable:true,nullable:true, hidden:true, dispunitType:"text", },
    {name:"createtime", label:"记录创建时间", editable:true,nullable:true, hidden:true, dispunitType:"time", }
  ]
}
