viewModels.prod_Main_Base = {
  id:"7cf9bdaf-802a-4070-864e-b47938fc5b6a",
  name:"prod_Main_Base",
  dataName:"prod_Main_Base",
  colModel:[
    {name:"ncpRowSelect", label:" ", width:20, hidden:false, sortable:false, search:false, resizable:false, editable:false, canEdit:false, edittype:"checkbox", dispunitType:"checkbox"},    {name:"name", label:"名称", width:250, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, edittype:"text", dispunitType:"text"},
    {name:"code", label:"编码", width:270, hidden:true, sortable:false, search:false, resizable:false, editable:true, canEdit:false, edittype:"text", dispunitType:"text"},
    {name:"prodtype", label:"商品类型", width:80, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:false, edittype:"text", dispunitType:"text"},
    {name:"property_type_xml", label:"属性类型", width:60, hidden:true, sortable:false, search:false, resizable:true, editable:true, canEdit:true, edittype:"text", dispunitType:"text"},
    {name:"description", label:"描述", width:150, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, edittype:"text", dispunitType:"text"},
    {name:"isonsale", label:"是否在售", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:true, edittype:"checkbox", dispunitType:"checkbox"},
    {name:"all_sale_num", label:"总销售数", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:false, edittype:"text", dispunitType:"decimal"},
    {name:"monthly_sale_num", label:"月销售数", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:false, edittype:"text", dispunitType:"decimal"},
    {name:"all_comment_num", label:"总评论数", width:60, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:false, edittype:"text", dispunitType:"decimal"},
    {name:"shop_id", label:"店铺Id", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, canEdit:false, edittype:"text", dispunitType:"text"},
    {name:"shopname", label:"店铺名称", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:false, edittype:"text", dispunitType:"text"},
    {name:"source_prod_id", label:"源商品Id", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, canEdit:false, edittype:"text", dispunitType:"text"},
    {name:"create_time", label:"创建时间", width:140, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:false, edittype:"text", formatter:timeFormater, dispunitType:"time"},
    {name:"edit_user_id", label:"编辑人Id", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, canEdit:false, edittype:"text", dispunitType:"text"},
    {name:"id", label:"Id", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, canEdit:false, edittype:"text", dispunitType:"text"},
    {name:"ltsys_prodtype_id", label:"商品类型Id", width:0, hidden:true, sortable:false, search:false, resizable:true, editable:true, canEdit:true, edittype:"text", dispunitType:"text"},
    {name:"modify_time", label:"修改时间", width:140, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:false, edittype:"text", formatter:timeFormater, dispunitType:"time"},
    {name:"username", label:"编辑人", width:100, hidden:false, sortable:false, search:false, resizable:true, editable:true, canEdit:false, edittype:"text", dispunitType:"text"}
  ],
  dispUnitModel:[
    {name:"name", label:"名称", editable:true,dispunitType:"text", },
    {name:"code", label:"编码", editable:false,dispunitType:"text", },
    {name:"prodtype", label:"商品类型", editable:false,dispunitType:"text", },
    {name:"property_type_xml", label:"属性类型", editable:true,dispunitType:"text", },
    {name:"description", label:"描述", editable:true,dispunitType:"text", },
    {name:"isonsale", label:"是否在售", editable:true,dispunitType:"checkbox", },
    {name:"all_sale_num", label:"总销售数", editable:false,dispunitType:"decimal", },
    {name:"monthly_sale_num", label:"月销售数", editable:false,dispunitType:"decimal", },
    {name:"all_comment_num", label:"总评论数", editable:false,dispunitType:"decimal", },
    {name:"shop_id", label:"店铺Id", editable:false,dispunitType:"text", },
    {name:"shopname", label:"店铺名称", editable:false,dispunitType:"text", },
    {name:"source_prod_id", label:"源商品Id", editable:false,dispunitType:"text", },
    {name:"create_time", label:"创建时间", editable:false,dispunitType:"time", },
    {name:"edit_user_id", label:"编辑人Id", editable:false,dispunitType:"text", },
    {name:"id", label:"Id", editable:false,dispunitType:"text", },
    {name:"ltsys_prodtype_id", label:"商品类型Id", editable:true,dispunitType:"text", },
    {name:"modify_time", label:"修改时间", editable:false,dispunitType:"time", },
    {name:"username", label:"编辑人", editable:false,dispunitType:"text", }
  ]
}
