paramWinModels.driveToNextUserSelector = {
  id:"e650187a-d8c1-480e-aa62-817e8edc3686",
  name:"driveToNextUserSelector",
  units:{
    username:{
      id:"46690820-a8ef-442d-bf71-c9657b8da6e3",
      name:"username",
      label:"姓名",
      valueType:valueType.string,
      inputHelpType:"",
      inputHelpName:"",
      decimalNum:"0",
      valueLength:40,
      isMultiValue:false,
      isNullable:true,
      isEditable:true,
      unitType:"text",
      defaultValue:"",
    },
    teamid:{
      id:"4f57eab7-ee80-4833-85a2-f7570b6ddb16",
      name:"teamid",
      label:"团队id",
      valueType:valueType.string,
      inputHelpType:"",
      inputHelpName:"",
      decimalNum:"0",
      valueLength:40,
      isMultiValue:false,
      isNullable:true,
      isEditable:true,
      unitType:"text",
      defaultValue:"",
    },
    teamname:{
      id:"aeca3898-ad24-4b8c-b4c2-149fb7805078",
      name:"teamname",
      label:"团队名",
      valueType:valueType.string,
      inputHelpType:"list",
      inputHelpName:"dataHelper.team.memberTeam",
      decimalNum:"0",
      valueLength:40,
      isMultiValue:false,
      isNullable:true,
      isEditable:true,
      unitType:"list",
      maps:{"teamid":"teamid","teamname":"teamname"},
      list:{
        name:"dataHelper.team.memberTeam",
        columns:[{field:"teamname",valueType:valueType.string,title:"团队名",width:200,hidden:false},
{field:"teamid",valueType:valueType.string,title:"团队id",width:0,hidden:true},
{field:"memberid",valueType:valueType.string,title:"memberid",width:0,hidden:true}
        ]
      },
      defaultValue:"",
    }
  }
}
