paramWinModels.queryYMWZhanQu = {
  id:24,
  name:"queryYMWZhanQu",
  units:{
    diseaseName:{
      id:156,
      name:"diseaseName",
      label:"传染病",
      valueType:valueType.string,
      inputHelpType:"list",
      inputHelpName:"crb.baseData.disease",
      decimalNum:"0",
      valueLength:20,
      isMultiValue:false,
      isNullable:false,
      unitType:"list",
      maps:{"diseaseId":"id","diseaseName":"name","diseaseCode":"code"},
      list:{
        name:"crb.baseData.disease",
        columns:[{field:"id",valueType:valueType.decimal,title:"id",width:0,hidden:true},
{field:"name",valueType:valueType.string,title:"名称",width:150,hidden:false},
{field:"code",valueType:valueType.string,title:"编码",width:0,hidden:true}
        ]
      },
      defaultValue:"合计",
    },
    monthValue:{
      id:153,
      name:"monthValue",
      label:"月份",
      valueType:valueType.string,
      inputHelpType:"list",
      inputHelpName:"crb.baseData.month",
      decimalNum:"0",
      valueLength:2,
      isMultiValue:false,
      isNullable:true,
      unitType:"list",
      maps:{"monthValue":"value"},
      list:{
        name:"crb.baseData.month",
        columns:[{field:"value",valueType:valueType.string,title:"月份",width:100,hidden:false}
        ]
      },
      defaultValue:"",
    },
    weekValue:{
      id:154,
      name:"weekValue",
      label:"周次",
      valueType:valueType.string,
      inputHelpType:"list",
      inputHelpName:"crb.baseData.week",
      decimalNum:"0",
      valueLength:2,
      isMultiValue:false,
      isNullable:true,
      unitType:"list",
      maps:{"weekValue":"value"},
      list:{
        name:"crb.baseData.week",
        columns:[{field:"value",valueType:valueType.string,title:"周次",width:100,hidden:false}
        ]
      },
      defaultValue:"",
    },
    diseaseId:{
      id:155,
      name:"diseaseId",
      label:"传染病Id",
      valueType:valueType.decimal,
      inputHelpType:"",
      inputHelpName:"",
      decimalNum:"0",
      valueLength:11,
      isMultiValue:false,
      isNullable:false,
      unitType:"decimal",
      defaultValue:"1",
    },
    yearValue:{
      id:152,
      name:"yearValue",
      label:"年份",
      valueType:valueType.string,
      inputHelpType:"list",
      inputHelpName:"crb.baseData.year",
      decimalNum:"0",
      valueLength:4,
      isMultiValue:false,
      isNullable:false,
      unitType:"list",
      maps:{"yearValue":"value"},
      list:{
        name:"crb.baseData.year",
        columns:[{field:"value",valueType:valueType.string,title:"年份",width:100,hidden:false}
        ]
      },
      defaultValue:"2013",
    },
    diseaseCode:{
      id:157,
      name:"diseaseCode",
      label:"传染病编码",
      valueType:valueType.string,
      inputHelpType:"",
      inputHelpName:"",
      decimalNum:"0",
      valueLength:20,
      isMultiValue:false,
      isNullable:false,
      unitType:"text",
      defaultValue:"hj",
    }
  }
}
