paramWinModels.queryYMW = {
  id:18,
  name:"queryYMW",
  units:{
    monthValue:{
      id:124,
      name:"monthValue",
      label:"月",
      valueType:valueType.string,
      inputHelpType:"list",
      inputHelpName:"crb.baseData.month",
      decimalNum:"0",
      valueLength:2,
      isMultiValue:false,
      isNullable:true,
      unitType:"list",
      maps:{"monthValue":"value"},
      list:{
        name:"crb.baseData.month",
        columns:[{field:"value",valueType:valueType.string,title:"月份",width:100,hidden:false}
        ]
      },
      defaultValue:"",
    },
    weekValue:{
      id:125,
      name:"weekValue",
      label:"周",
      valueType:valueType.string,
      inputHelpType:"list",
      inputHelpName:"crb.baseData.week",
      decimalNum:"0",
      valueLength:2,
      isMultiValue:false,
      isNullable:true,
      unitType:"list",
      maps:{"weekValue":"value"},
      list:{
        name:"crb.baseData.week",
        columns:[{field:"value",valueType:valueType.string,title:"周次",width:100,hidden:false}
        ]
      },
      defaultValue:"",
    },
    yearValue:{
      id:123,
      name:"yearValue",
      label:"年",
      valueType:valueType.string,
      inputHelpType:"list",
      inputHelpName:"crb.baseData.year",
      decimalNum:"0",
      valueLength:4,
      isMultiValue:false,
      isNullable:false,
      unitType:"list",
      maps:{"yearValue":"value"},
      list:{
        name:"crb.baseData.year",
        columns:[{field:"value",valueType:valueType.string,title:"年份",width:100,hidden:false}
        ]
      },
      defaultValue:"2013",
    }
  }
}
