paramWinModels.queryYearMonthDisease = {
  id:19,
  name:"queryYearMonthDisease",
  units:{
    diseaseName:{
      id:129,
      name:"diseaseName",
      label:"传染病",
      valueType:valueType.string,
      inputHelpType:"list",
      inputHelpName:"crb.baseData.disease",
      decimalNum:"0",
      valueLength:20,
      isMultiValue:false,
      isNullable:false,
      unitType:"list",
      maps:{"diseaseId":"id","diseaseName":"name"},
      list:{
        name:"crb.baseData.disease",
        columns:[{field:"id",valueType:valueType.decimal,title:"id",width:0,hidden:true},
{field:"name",valueType:valueType.string,title:"名称",width:150,hidden:false},
{field:"code",valueType:valueType.string,title:"编码",width:0,hidden:true}
        ]
      },
      defaultValue:"合计",
    },
    monthValue:{
      id:127,
      name:"monthValue",
      label:"月份",
      valueType:valueType.string,
      inputHelpType:"list",
      inputHelpName:"crb.baseData.month",
      decimalNum:"0",
      valueLength:2,
      isMultiValue:false,
      isNullable:true,
      unitType:"list",
      maps:{"monthValue":"value"},
      list:{
        name:"crb.baseData.month",
        columns:[{field:"value",valueType:valueType.string,title:"月份",width:100,hidden:false}
        ]
      },
      defaultValue:"",
    },
    diseaseId:{
      id:128,
      name:"diseaseId",
      label:"传染病Id",
      valueType:valueType.decimal,
      inputHelpType:"",
      inputHelpName:"",
      decimalNum:"0",
      valueLength:11,
      isMultiValue:false,
      isNullable:false,
      unitType:"decimal",
      defaultValue:"1",
    },
    yearValue:{
      id:126,
      name:"yearValue",
      label:"年份",
      valueType:valueType.string,
      inputHelpType:"list",
      inputHelpName:"crb.baseData.year",
      decimalNum:"0",
      valueLength:4,
      isMultiValue:false,
      isNullable:false,
      unitType:"list",
      maps:{"yearValue":"value"},
      list:{
        name:"crb.baseData.year",
        columns:[{field:"value",valueType:valueType.string,title:"年份",width:100,hidden:false}
        ]
      },
      defaultValue:"2013",
    }
  }
}
